### ISSUE TITLE
Did rlig get acccidentally deleted?

### ISSUE THREAD

**Issue by kenmcd** [RosaWagner/Borel#11]
A previous commit moved some `calt` code to `rlig`...
**Moved calt feature to rlig and fixed croat issue** - https://github.com/RosaWagner/Borel/commit/80b313baf9b4bd8025d04a760febcc761905f845
And the v1.004 TTF from that commit did have `rlig` in it. 
You had made a note that the move to `rlig` was to deal with some Word issue - which is why I was trying to understand what was done and why.

In the current v1.006 TTF the `rlig` is not there.
So has this been reversed on purpose?
Or did it just get missed during some additional updates?

**Comment by RosaWagner** [comment]
I reversed it to calt cause rlig was not working everywhere as i thought and I didn’t want to confuse users more when updating on google fonts.

**Comment by kenmcd** [comment]
Thanks.
