### ISSUE TITLE
La police ne prend pas en charge les caractères "ã" et "õ", très utilisés en portugais.

### ISSUE THREAD

**Issue by ditthales** [RosaWagner/Borel#2]
Je voudrais utiliser la police pour une application au Brésil mais elle ne prend pas en charge les caractères "ã" et "õ". S'il vous plaît, pourriez-vous réparer cela?

**Comment by RosaWagner** [comment]
C'était prévu :) les fichiers sont dans `Borel/fonts/ttf`

**Comment by ditthales** [comment]
Merci beaucoup vraiment! Moi et mon équipe sommes très heureux de votre aide.
